#!/bin/bash

# Colors
BLACK='\033[0;30m'
RED='\033[0;31m'
GREEN='\033[0;32m'
BROWN='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT_GRAY='\033[0;37m'

DARK_GRAY='\033[1;30m'
LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
YELLOW='\033[1;33m'
LIGHT_BLUE='\033[1;34m'
LIGHT_PURPLE='\033[1;35m'
LIGHT_CYAN='\033[1;36m'
WHITE='\033[1;37m'
NC='\033[0m'

# user@host
USER=$(whoami)
HOST=$(cat /etc/hostname)
printf "${LIGHT_PURPLE}$USER@$HOST${NC}\n"

# distro
DISTRO=$(head -1 /etc/os-release | grep -o '"[^"]\+"' | sed 's/"//g')
printf "${BLUE}os${NC}\t$DISTRO\n"

# kernel
KERNEL=$(uname -r)
printf "${BLUE}kernel${NC}\t$KERNEL\n"

# uptime
UPTIME=$(cat /proc/uptime | awk '{print $1}')
printf "${BLUE}uptime${NC}\t"
echo $UPTIME | awk '{printf "%dd %dh %dm\n", $1/86400, ($1%86400)/3600, ($1%3600)/60}'

# packages count
PACKAGES=$(pacman -Q | wc -l)
printf "${BLUE}pkgs${NC}\t$PACKAGES\n"

# memory
MEMORY=$(free -m | sed -n '2p' | awk '{print $3 "M / " $2 "M"}')
printf "${BLUE}memory${NC}\t$MEMORY\n"
